### ISSUE TITLE
Wrong date for sunrise time

### ISSUE THREAD

**Issue by beekarthik** [Triggertrap/sun-js#3]
When I find the sunrise and sunset time with respect to my current location, sunrise is calculated with tomorrow's date instead of today's date.

**Comment by ascorbic** [comment]
Hey. It's been a long time since I looked at this, but I'm pretty sure it gives the next sunrise, so if you're calling it after sunrise then it'll be tomorrow's. If you do it at midnight then you'll get the current day.
